// Employee Data Action Types
export const EMPLOYEES_GET_DATA = 'EMPLOYEES_GET_DATA';
export const EMPLOYEES_GET_DATA_SUCCESS = 'EMPLOYEES_GET_DATA_SUCCESS';
export const EMPLOYEES_GET_DATA_ERROR = 'EMPLOYEES_GET_DATA_ERROR';

export const GET_EMPLOYEE_DATA_START = 'GET_EMPLOYEE_DATA_START';
export const GET_EMPLOYEE_DATA_SUCCESS = 'GET_EMPLOYEE_DATA_SUCCESS';
export const GET_EMPLOYEE_DATA_ERROR = 'GET_EMPLOYEE_DATA_ERROR';
