// Employee Data Action Types
export const EMPLOYEES_GET_DATA = 'EMPLOYEES_GET_DATA';
export const EMPLOYEES_GET_DATA_SUCCESS = 'EMPLOYEES_GET_DATA_SUCCESS';
export const EMPLOYEES_GET_DATA_ERROR = 'EMPLOYEES_GET_DATA_ERROR';